name: Keep Render App Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 15 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Render App Alive
        run: curl -X GET "https://personal-pro-atg8.onrender.com/"
